pretrained: 'facebook/wav2vec2-base'
sampling_rate: 16000
contrastive_margin: 1.0
device: 'cpu'

metrics_avg_type: 'micro'
from_pretrained: false
emb_pretrained: 'checkpoint.pt' 

train_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}

val_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 4 
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}

optimizer:
  lr: 0.0001
  betas: [0.9, 0.98]
  weight_decay: 1e-2
  model_size: 768
  warmup_steps: 500
  factor: 1.2 

classifier:
  num_labels: 5
  dropout: 0.3
  pooling_kernel_size: 2
  conv_kernel_size: 3
  hidden_size: 768
  project_size: 128

