pretrained: 'facebook/wav2vec2-base'
sampling_rate: 16000
contrastive_margin: 1.0
device: 'cuda:0'

metrics_avg_type: 'micro'
loss_weights: [0.9, 2.3, 0.3, 4.5, 5.1]

train_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  ratio: 1.0
  sr: ${sampling_rate}

train_dataset_syn:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  ratio: 0.9
  sr: ${sampling_rate}

val_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 4 
  shuffle: true
  num_workers: 4
  ratio: 1.0
  sr: ${sampling_rate}

optimizer:
  lr: 1e-4
  betas: [0.9, 0.98]
  weight_decay: 1e-2
  model_size: 768
  warmup_steps: 1000
  factor: 1

classifier:
  num_labels: 5
  dropout: 0.3
  pooling_kernel_size: 2
  conv_kernel_size: 3
  hidden_size: 768
  project_size: 128

