pretrained: 'facebook/wav2vec2-base'
sampling_rate: 16000
contrastive_margin: 1.0
device: 'cuda:0'

train_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}

val_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 4 
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}

optimizer:
  lr: 0.001
  betas: [0.9, 0.98]
  weight_decay: 1e-2
  model_size: 768
  warmup_steps: 500
  factor: 1.2
