pretrained: 'facebook/wav2vec2-base'
sampling_rate: 16000

train_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}

val_dataset:
  dirs:
    angry: '.'
    happy: '.'
    neutral: '.'
    sad: '.'
    surprise: '.'
  batch_size: 8
  shuffle: true
  num_workers: 4
  sr: ${sampling_rate}